### ISSUE TITLE
Verzoek tot contact

### ISSUE THREAD

**Issue by jwktje** [wimb0/saj_modbus#1]
Via Google en Tweakers kwam ik op deze repo. Ik probeer (middels een ESP32/Arduino bordje) de modbus op RS485 uit te lezen van een SAJ inverter maar ik loop hier op vast. Ik zie dat jij hier wel succes hebt gehad. Ik zou je advies goed kunnen gebruiken. Hoe kan ik met je in contact komen? Dit hoeft uiteraard niet voor niets.

**Comment by wimb0** [comment]
Alle info die ik heb staat in deze repo, inclusief de SAJ documentatie. Daarmee zou je iets moeten kunnen bouwen voor gebruik met een ESP module. Deze code is slechts een voorbeeld om de inverter met Python uit te lezen,
