### ISSUE TITLE
Unable to retreive data fram SAJ HS2-5K-S2-X

### ISSUE THREAD

**Issue by pizzulicchio** [wimb0/saj_modbus#2]
Hi,
i'm testing your script on my SAJ Solar Inverter model : saj HS2-5K-S2-X
I'm using the AIO3 wifi modbus module that is connected to the inverter.

Here the output of your python scripts.
![SajModbus](https://github.com/wimb0/saj_modbus/assets/5867711/7218e01e-d7c8-469b-806d-05d639884654)

read_invertor_details.py is be able to read data, but read_realtime_data.py seems to not shown any data.

What can i test for debug?

**Comment by wimb0** [comment]
The H2 is not supported by these scripts.
The read_realtime_data.py does not have the modbus registers for the H2 inverters.

See https://github.com/stanus74/home-assistant-saj-h2-modbus for connecting to H2 inverters.

**Comment by pizzulicchio** [comment]
I'm using that plugin for home assitant and it's working, but I'd like to have something working for domoticz too. 
Home assitant it's great but the automation with blockly of domoticz it's my favourite!

**Comment by wimb0** [comment]
They have a PDF file which lists which modbus registers to use.
Maybe you can add them to a custom version of this script for use with your H2.

**Comment by pizzulicchio** [comment]
[H2-3~6K-S2 single phase communication protocol -2022.12.02-EN.pdf](https://github.com/user-attachments/files/15938374/H2-3.6K-S2.single.phase.communication.protocol.-2022.12.02-EN.pdf)
This is the pdf for the modbus registers. 
I'm honest... I don't have the knowledge about this protocol and python... so I'm trying to edit your file.. can you give me some tips? I apologize for the embarrassing request..

**Comment by wimb0** [comment]
You can use some python code from https://github.com/stanus74/home-assistant-saj-h2-modbus/blob/main/custom_components/saj_modbus/hub.py
From line 123 you can see the script reads data from the inverter.
It reads 29 registers, starting from address 0x8F00.
In my scripts, it starts reading at address 256 and reads the next 60. See line 26 and 27 in https://github.com/wimb0/saj_modbus/blob/main/read_realtime_data.py.

Maybe this helps you getting started?

**Comment by pizzulicchio** [comment]
Thank you very much. It's not easy for me, but i I really appreciate your help.

**Comment by wimb0** [comment]
Good luck, and I hope you can get it to work.
I'll close the issue, but you can still leave a comment here if needed.
